
#index.html使用分页效果
gems: [jekyll-paginate]
paginate: 2
paginate_path: "page:num"
#index.html使用分页效果 结束

baseurl: /

#静态内容请求路径
static_path: /static

port: 4001

#搜索功能

#搜索功能


# RSS 订阅
name:         Not Only Coffee
description:  blog to share IT Knowledge
url:          https://notonlycoffee.github.io/
# RSS 订阅 结束